export const mock2 = {
  session: {
    'timestamp': '2024-05-05T14:25:59.099Z',
    'data': {
      'WeekendInfo': {
        'TrackName': 'oulton international',
        'TrackID': 180,
        'TrackLength': '4.29 km',
        'TrackLengthOfficial': '4.33 km',
        'TrackDisplayName': 'Oulton Park Circuit',
        'TrackDisplayShortName': 'Oulton',
        'TrackConfigName': 'International',
        'TrackCity': 'Little Budworth',
        'TrackCountry': 'England',
        'TrackAltitude': '69.47 m',
        'TrackLatitude': '53.180009 m',
        'TrackLongitude': '-2.612779 m',
        'TrackNorthOffset': '3.0267 rad',
        'TrackNumTurns': 17,
        'TrackPitSpeedLimit': '49.97 kph',
        'TrackType': 'road course',
        'TrackDirection': 'neutral',
        'TrackWeatherType': 'Realistic',
        'TrackSkies': 'Dynamic',
        'TrackSurfaceTemp': '26.14 C',
        'TrackAirTemp': '20.14 C',
        'TrackAirPressure': '29.96 Hg',
        'TrackWindVel': '2.44 m/s',
        'TrackWindDir': '4.09 rad',
        'TrackRelativeHumidity': '34 %',
        'TrackFogLevel': '0 %',
        'TrackPrecipitation': '0 %',
        'TrackCleanup': 1,
        'TrackDynamicTrack': 1,
        'TrackVersion': '2024.03.28.01',
        'SeriesID': 139,
        'SeasonID': 4730,
        'SessionID': 237386029,
        'SubSessionID': 68581204,
        'LeagueID': 0,
        'Official': 1,
        'RaceWeek': 7,
        'EventType': 'Race',
        'Category': 'SportsCar',
        'SimMode': 'full',
        'TeamRacing': 0,
        'MinDrivers': 0,
        'MaxDrivers': 1,
        'DCRuleSet': 'None',
        'QualifierMustStartRace': 0,
        'NumCarClasses': 1,
        'NumCarTypes': 2,
        'HeatRacing': 0,
        'BuildType': 'Release',
        'BuildTarget': 'Members',
        'BuildVersion': '2024.05.01.02',
        'WeekendOptions': {
          'NumStarters': 12,
          'StartingGrid': '2x2 inline pole on left',
          'QualifyScoring': 'best lap',
          'CourseCautions': 'local',
          'StandingStart': 1,
          'ShortParadeLap': 0,
          'Restarts': 'double file lapped cars behind',
          'WeatherType': 'Realistic',
          'Skies': 'Dynamic',
          'WindDirection': 'N',
          'WindSpeed': '3.22 km/h',
          'WeatherTemp': '25.56 C',
          'RelativeHumidity': '45 %',
          'FogLevel': '0 %',
          'TimeOfDay': '1:50 pm',
          'Date': '2024-05-04T00:00:00.000Z',
          'EarthRotationSpeedupFactor': 1,
          'Unofficial': 0,
          'CommercialMode': 'consumer',
          'NightMode': 'variable',
          'IsFixedSetup': 0,
          'StrictLapsChecking': 'default',
          'HasOpenRegistration': 0,
          'HardcoreLevel': 1,
          'NumJokerLaps': 0,
          'IncidentLimit': 17,
          'FastRepairsLimit': 1,
          'GreenWhiteCheckeredLimit': 0
        },
        'TelemetryOptions': {
          'TelemetryDiskFile': ''
        }
      },
      'SessionInfo': {
        'Sessions': [
          {
            'SessionNum': 0,
            'SessionLaps': 'unlimited',
            'SessionTime': '180.0000 sec',
            'SessionNumLapsToAvg': 0,
            'SessionType': 'Practice',
            'SessionTrackRubberState': 'moderately high usage',
            'SessionName': 'PRACTICE',
            'SessionSubType': null,
            'SessionSkipped': 0,
            'SessionRunGroupsUsed': 0,
            'SessionEnforceTireCompoundChange': 0,
            'ResultsPositions': [
              {
                'Position': 1,
                'ClassPosition': 0,
                'CarIdx': 10,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 0,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 2,
                'ClassPosition': 1,
                'CarIdx': 1,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 0,
                'JokerLapsComplete': 0,
                'LapsDriven': 0.562,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 3,
                'ClassPosition': 2,
                'CarIdx': 2,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 0,
                'JokerLapsComplete': 0,
                'LapsDriven': 0.244,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 4,
                'ClassPosition': 3,
                'CarIdx': 3,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 0,
                'JokerLapsComplete': 0,
                'LapsDriven': 0.598,
                'Incidents': 1,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 5,
                'ClassPosition': 4,
                'CarIdx': 4,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 0,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 6,
                'ClassPosition': 5,
                'CarIdx': 5,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 0,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 7,
                'ClassPosition': 6,
                'CarIdx': 6,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 0,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 8,
                'ClassPosition': 7,
                'CarIdx': 7,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 0,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 9,
                'ClassPosition': 8,
                'CarIdx': 8,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 0,
                'JokerLapsComplete': 0,
                'LapsDriven': 0.586,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 10,
                'ClassPosition': 9,
                'CarIdx': 9,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 0,
                'JokerLapsComplete': 0,
                'LapsDriven': 0.859,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 11,
                'ClassPosition': 10,
                'CarIdx': 11,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 0,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              }
            ],
            'ResultsFastestLap': [
              {
                'CarIdx': 255,
                'FastestLap': 0,
                'FastestTime': -1
              }
            ],
            'ResultsAverageLapTime': -1,
            'ResultsNumCautionFlags': 0,
            'ResultsNumCautionLaps': 0,
            'ResultsNumLeadChanges': 0,
            'ResultsLapsComplete': -1,
            'ResultsOfficial': 1
          },
          {
            'SessionNum': 1,
            'SessionLaps': 2,
            'SessionTime': '480.0000 sec',
            'SessionNumLapsToAvg': 0,
            'SessionType': 'Lone Qualify',
            'SessionTrackRubberState': 'carry over',
            'SessionName': 'QUALIFY',
            'SessionSubType': null,
            'SessionSkipped': 0,
            'SessionRunGroupsUsed': 0,
            'SessionEnforceTireCompoundChange': 0,
            'ResultsPositions': [
              {
                'Position': 1,
                'ClassPosition': 0,
                'CarIdx': 9,
                'Lap': 1,
                'Time': 119.4715,
                'FastestLap': 1,
                'FastestTime': 119.4715,
                'LastTime': 119.8479,
                'LapsLed': 0,
                'LapsComplete': 2,
                'JokerLapsComplete': 0,
                'LapsDriven': 3.761,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 2,
                'ClassPosition': 1,
                'CarIdx': 1,
                'Lap': 2,
                'Time': 136.1046,
                'FastestLap': 2,
                'FastestTime': 136.1046,
                'LastTime': 136.1046,
                'LapsLed': 0,
                'LapsComplete': 2,
                'JokerLapsComplete': 0,
                'LapsDriven': 3.013,
                'Incidents': 3,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 3,
                'ClassPosition': 2,
                'CarIdx': 10,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 1,
                'JokerLapsComplete': 0,
                'LapsDriven': 3.24,
                'Incidents': 2,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 4,
                'ClassPosition': 3,
                'CarIdx': 2,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 1,
                'JokerLapsComplete': 0,
                'LapsDriven': 3.218,
                'Incidents': 5,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 5,
                'ClassPosition': 4,
                'CarIdx': 3,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 0,
                'JokerLapsComplete': 0,
                'LapsDriven': 1.054,
                'Incidents': 2,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 6,
                'ClassPosition': 5,
                'CarIdx': 4,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 1,
                'JokerLapsComplete': 0,
                'LapsDriven': 2.967,
                'Incidents': 11,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 7,
                'ClassPosition': 6,
                'CarIdx': 5,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 0,
                'JokerLapsComplete': 0,
                'LapsDriven': 2.11,
                'Incidents': 12,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 8,
                'ClassPosition': 7,
                'CarIdx': 6,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 0,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 9,
                'ClassPosition': 8,
                'CarIdx': 7,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 0,
                'JokerLapsComplete': 0,
                'LapsDriven': 0.741,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 10,
                'ClassPosition': 9,
                'CarIdx': 8,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 0,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 11,
                'ClassPosition': 10,
                'CarIdx': 11,
                'Lap': 0,
                'Time': -1,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 0,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              }
            ],
            'ResultsFastestLap': [
              {
                'CarIdx': 9,
                'FastestLap': 1,
                'FastestTime': 119.4715
              }
            ],
            'ResultsAverageLapTime': -1,
            'ResultsNumCautionFlags': 0,
            'ResultsNumCautionLaps': 0,
            'ResultsNumLeadChanges': 0,
            'ResultsLapsComplete': -1,
            'ResultsOfficial': 1
          },
          {
            'SessionNum': 2,
            'SessionLaps': 8,
            'SessionTime': 'unlimited',
            'SessionNumLapsToAvg': 0,
            'SessionType': 'Race',
            'SessionTrackRubberState': 'carry over',
            'SessionName': 'RACE',
            'SessionSubType': null,
            'SessionSkipped': 0,
            'SessionRunGroupsUsed': 0,
            'SessionEnforceTireCompoundChange': 0,
            'ResultsPositions': [
              {
                'Position': 1,
                'ClassPosition': 0,
                'CarIdx': 10,
                'Lap': 0,
                'Time': 0,
                'FastestLap': 4,
                'FastestTime': 114.5963,
                'LastTime': 114.0953,
                'LapsLed': 6,
                'LapsComplete': 6,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 2,
                'ClassPosition': 1,
                'CarIdx': 5,
                'Lap': 0,
                'Time': 16.685,
                'FastestLap': 3,
                'FastestTime': 115.8815,
                'LastTime': 122.3633,
                'LapsLed': 0,
                'LapsComplete': 6,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 3,
                'ClassPosition': 2,
                'CarIdx': 3,
                'Lap': 0,
                'Time': 20.0893,
                'FastestLap': 6,
                'FastestTime': 116.9916,
                'LastTime': 116.9916,
                'LapsLed': 0,
                'LapsComplete': 6,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 4,
                'ClassPosition': 3,
                'CarIdx': 4,
                'Lap': 0,
                'Time': 49.0576,
                'FastestLap': 5,
                'FastestTime': 122.2456,
                'LastTime': 122.2456,
                'LapsLed': 0,
                'LapsComplete': 5,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 5,
                'ClassPosition': 4,
                'CarIdx': 8,
                'Lap': 0,
                'Time': 103.8083,
                'FastestLap': 3,
                'FastestTime': 120.4697,
                'LastTime': 183.6046,
                'LapsLed': 0,
                'LapsComplete': 5,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 6,
                'ClassPosition': 5,
                'CarIdx': 9,
                'Lap': 1,
                'Time': 117.1251,
                'FastestLap': 5,
                'FastestTime': 119.699,
                'LastTime': 119.699,
                'LapsLed': 0,
                'LapsComplete': 5,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 7,
                'ClassPosition': 6,
                'CarIdx': 7,
                'Lap': 1,
                'Time': 118.2298,
                'FastestLap': 4,
                'FastestTime': 117.1502,
                'LastTime': 118.9481,
                'LapsLed': 0,
                'LapsComplete': 5,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 8,
                'ClassPosition': 7,
                'CarIdx': 2,
                'Lap': 1,
                'Time': 124.7466,
                'FastestLap': 4,
                'FastestTime': 116.9326,
                'LastTime': 117.177,
                'LapsLed': 0,
                'LapsComplete': 5,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 9,
                'ClassPosition': 8,
                'CarIdx': 11,
                'Lap': 1,
                'Time': 142.8589,
                'FastestLap': 2,
                'FastestTime': 120.979,
                'LastTime': -1,
                'LapsLed': 0,
                'LapsComplete': 5,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              },
              {
                'Position': 10,
                'ClassPosition': 9,
                'CarIdx': 1,
                'Lap': 3,
                'Time': 27.7939,
                'FastestLap': -1,
                'FastestTime': -1,
                'LastTime': 132.2231,
                'LapsLed': 0,
                'LapsComplete': 2,
                'JokerLapsComplete': 0,
                'LapsDriven': 0,
                'Incidents': 0,
                'ReasonOutId': 0,
                'ReasonOutStr': 'Running'
              }
            ],
            'ResultsFastestLap': [
              {
                'CarIdx': 10,
                'FastestLap': 4,
                'FastestTime': 114.5963
              }
            ],
            'ResultsAverageLapTime': 117.6541,
            'ResultsNumCautionFlags': 0,
            'ResultsNumCautionLaps': 0,
            'ResultsNumLeadChanges': 0,
            'ResultsLapsComplete': 6,
            'ResultsOfficial': 0
          }
        ]
      },
      'QualifyResultsInfo': {
        'Results': [
          {
            'Position': 0,
            'ClassPosition': 0,
            'CarIdx': 9,
            'FastestLap': 1,
            'FastestTime': 119.4715
          },
          {
            'Position': 1,
            'ClassPosition': 1,
            'CarIdx': 1,
            'FastestLap': 2,
            'FastestTime': 136.1046
          },
          {
            'Position': 2,
            'ClassPosition': 2,
            'CarIdx': 10,
            'FastestLap': 0,
            'FastestTime': -1
          },
          {
            'Position': 3,
            'ClassPosition': 3,
            'CarIdx': 2,
            'FastestLap': 0,
            'FastestTime': -1
          },
          {
            'Position': 4,
            'ClassPosition': 4,
            'CarIdx': 3,
            'FastestLap': 0,
            'FastestTime': -1
          },
          {
            'Position': 5,
            'ClassPosition': 5,
            'CarIdx': 4,
            'FastestLap': 0,
            'FastestTime': -1
          },
          {
            'Position': 6,
            'ClassPosition': 6,
            'CarIdx': 5,
            'FastestLap': 0,
            'FastestTime': -1
          },
          {
            'Position': 7,
            'ClassPosition': 7,
            'CarIdx': 7,
            'FastestLap': 0,
            'FastestTime': -1
          },
          {
            'Position': 8,
            'ClassPosition': 8,
            'CarIdx': 8,
            'FastestLap': 0,
            'FastestTime': -1
          },
          {
            'Position': 9,
            'ClassPosition': 9,
            'CarIdx': 11,
            'FastestLap': 0,
            'FastestTime': -1
          },
          {
            'Position': 10,
            'ClassPosition': 10,
            'CarIdx': 6,
            'FastestLap': 0,
            'FastestTime': -1
          }
        ]
      },
      'CameraInfo': {
        'Groups': [
          {
            'GroupNum': 1,
            'GroupName': 'Nose',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamNose'
              }
            ]
          },
          {
            'GroupNum': 2,
            'GroupName': 'Gearbox',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamGearbox'
              }
            ]
          },
          {
            'GroupNum': 3,
            'GroupName': 'Roll Bar',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamRoll Bar'
              }
            ]
          },
          {
            'GroupNum': 4,
            'GroupName': 'LF Susp',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamLF Susp'
              }
            ]
          },
          {
            'GroupNum': 5,
            'GroupName': 'LR Susp',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamLR Susp'
              }
            ]
          },
          {
            'GroupNum': 6,
            'GroupName': 'Gyro',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamGyro'
              }
            ]
          },
          {
            'GroupNum': 7,
            'GroupName': 'RF Susp',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamRF Susp'
              }
            ]
          },
          {
            'GroupNum': 8,
            'GroupName': 'RR Susp',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamRR Susp'
              }
            ]
          },
          {
            'GroupNum': 9,
            'GroupName': 'Cockpit',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamCockpit'
              }
            ]
          },
          {
            'GroupNum': 10,
            'GroupName': 'Blimp',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamBlimp'
              }
            ]
          },
          {
            'GroupNum': 11,
            'GroupName': 'Chopper',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamChopper'
              }
            ]
          },
          {
            'GroupNum': 12,
            'GroupName': 'Chase',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamChase'
              }
            ]
          },
          {
            'GroupNum': 13,
            'GroupName': 'Far Chase',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamFar Chase'
              }
            ]
          },
          {
            'GroupNum': 14,
            'GroupName': 'Rear Chase',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamRear Chase'
              }
            ]
          },
          {
            'GroupNum': 15,
            'GroupName': 'Pit Lane',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamPit Lane'
              }
            ]
          },
          {
            'GroupNum': 16,
            'GroupName': 'Pit Lane 2',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamPit Lane 2'
              }
            ]
          },
          {
            'GroupNum': 17,
            'GroupName': 'Scenic',
            'IsScenic': true,
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'Scenic_00'
              },
              {
                'CameraNum': 2,
                'CameraName': 'Scenic_01'
              },
              {
                'CameraNum': 3,
                'CameraName': 'Scenic_02'
              },
              {
                'CameraNum': 4,
                'CameraName': 'Scenic_03'
              },
              {
                'CameraNum': 5,
                'CameraName': 'Scenic_04'
              },
              {
                'CameraNum': 6,
                'CameraName': 'Scenic_05'
              },
              {
                'CameraNum': 7,
                'CameraName': 'Scenic_06'
              },
              {
                'CameraNum': 8,
                'CameraName': 'Scenic_07'
              },
              {
                'CameraNum': 9,
                'CameraName': 'Scenic_08'
              },
              {
                'CameraNum': 10,
                'CameraName': 'Scenic_09'
              },
              {
                'CameraNum': 11,
                'CameraName': 'Scenic_10'
              }
            ]
          },
          {
            'GroupNum': 18,
            'GroupName': 'TV1',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamTV1_00'
              },
              {
                'CameraNum': 2,
                'CameraName': 'CamTV1_01'
              },
              {
                'CameraNum': 3,
                'CameraName': 'CamTV1_02'
              },
              {
                'CameraNum': 4,
                'CameraName': 'CamTV1_03'
              },
              {
                'CameraNum': 5,
                'CameraName': 'CamTV1_04'
              },
              {
                'CameraNum': 6,
                'CameraName': 'CamTV1_05'
              },
              {
                'CameraNum': 7,
                'CameraName': 'CamTV1_06'
              },
              {
                'CameraNum': 8,
                'CameraName': 'CamTV1_07'
              },
              {
                'CameraNum': 9,
                'CameraName': 'CamTV1_08'
              },
              {
                'CameraNum': 10,
                'CameraName': 'CamTV1_09'
              },
              {
                'CameraNum': 11,
                'CameraName': 'CamTV1_10'
              }
            ]
          },
          {
            'GroupNum': 19,
            'GroupName': 'TV2',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamTV2_00'
              },
              {
                'CameraNum': 2,
                'CameraName': 'CamTV2_01'
              },
              {
                'CameraNum': 3,
                'CameraName': 'CamTV2_02'
              },
              {
                'CameraNum': 4,
                'CameraName': 'CamTV2_03'
              },
              {
                'CameraNum': 5,
                'CameraName': 'CamTV2_04'
              },
              {
                'CameraNum': 6,
                'CameraName': 'CamTV2_05'
              },
              {
                'CameraNum': 7,
                'CameraName': 'CamTV2_06'
              },
              {
                'CameraNum': 8,
                'CameraName': 'CamTV2_07'
              },
              {
                'CameraNum': 9,
                'CameraName': 'CamTV2_08'
              },
              {
                'CameraNum': 10,
                'CameraName': 'CamTV2_09'
              },
              {
                'CameraNum': 11,
                'CameraName': 'CamTV2_10'
              },
              {
                'CameraNum': 12,
                'CameraName': 'CamTV2_11'
              },
              {
                'CameraNum': 13,
                'CameraName': 'CamTV2_12'
              },
              {
                'CameraNum': 14,
                'CameraName': 'CamTV2_13'
              },
              {
                'CameraNum': 15,
                'CameraName': 'CamTV2_14'
              }
            ]
          },
          {
            'GroupNum': 20,
            'GroupName': 'TV3',
            'Cameras': [
              {
                'CameraNum': 1,
                'CameraName': 'CamTV3_00'
              },
              {
                'CameraNum': 2,
                'CameraName': 'CamTV3_01'
              },
              {
                'CameraNum': 3,
                'CameraName': 'CamTV3_02'
              },
              {
                'CameraNum': 4,
                'CameraName': 'CamTV3_03'
              },
              {
                'CameraNum': 5,
                'CameraName': 'CamTV3_04'
              },
              {
                'CameraNum': 6,
                'CameraName': 'CamTV3_05'
              },
              {
                'CameraNum': 7,
                'CameraName': 'CamTV3_06'
              },
              {
                'CameraNum': 8,
                'CameraName': 'CamTV3_07'
              },
              {
                'CameraNum': 9,
                'CameraName': 'CamTV3_08'
              },
              {
                'CameraNum': 10,
                'CameraName': 'CamTV3_09'
              },
              {
                'CameraNum': 11,
                'CameraName': 'CamTV3_10'
              }
            ]
          }
        ]
      },
      'RadioInfo': {
        'SelectedRadioNum': 0,
        'Radios': [
          {
            'RadioNum': 0,
            'HopCount': 2,
            'NumFrequencies': 5,
            'TunedToFrequencyNum': 0,
            'ScanningIsOn': 1,
            'Frequencies': [
              {
                'FrequencyNum': 0,
                'FrequencyName': '@SPECTATORS',
                'Priority': 0,
                'CarIdx': -1,
                'EntryIdx': -1,
                'ClubID': 0,
                'CanScan': 1,
                'CanSquawk': 1,
                'Muted': 0,
                'IsMutable': 1,
                'IsDeletable': 0
              },
              {
                'FrequencyNum': 1,
                'FrequencyName': '@DRIVERS',
                'Priority': 15,
                'CarIdx': -1,
                'EntryIdx': -1,
                'ClubID': 0,
                'CanScan': 1,
                'CanSquawk': 0,
                'Muted': 0,
                'IsMutable': 1,
                'IsDeletable': 0
              },
              {
                'FrequencyNum': 2,
                'FrequencyName': '@ALLTEAMS',
                'Priority': 12,
                'CarIdx': -1,
                'EntryIdx': -1,
                'ClubID': 0,
                'CanScan': 1,
                'CanSquawk': 0,
                'Muted': 0,
                'IsMutable': 1,
                'IsDeletable': 0
              },
              {
                'FrequencyNum': 3,
                'FrequencyName': '@RACECONTROL',
                'Priority': 80,
                'CarIdx': -1,
                'EntryIdx': -1,
                'ClubID': 0,
                'CanScan': 1,
                'CanSquawk': 0,
                'Muted': 0,
                'IsMutable': 0,
                'IsDeletable': 0
              },
              {
                'FrequencyNum': 4,
                'FrequencyName': '@PRIVATE',
                'Priority': 70,
                'CarIdx': -1,
                'EntryIdx': 12,
                'ClubID': 0,
                'CanScan': 1,
                'CanSquawk': 1,
                'Muted': 0,
                'IsMutable': 0,
                'IsDeletable': 0
              }
            ]
          }
        ]
      },
      'DriverInfo': {
        'DriverCarIdx': 63,
        'DriverUserID': 1041895,
        'PaceCarIdx': 0,
        'DriverHeadPosX': -0.416,
        'DriverHeadPosY': 0.344,
        'DriverHeadPosZ': 0.66,
        'DriverCarIsElectric': 0,
        'DriverCarIdleRPM': 875,
        'DriverCarRedLine': 7525,
        'DriverCarEngCylinderCount': 4,
        'DriverCarFuelKgPerLtr': 0.75,
        'DriverCarFuelMaxLtr': 44.987,
        'DriverCarMaxFuelPct': 1,
        'DriverCarGearNumForward': 6,
        'DriverCarGearNeutral': 1,
        'DriverCarGearReverse': 1,
        'DriverCarSLFirstRPM': 5600,
        'DriverCarSLShiftRPM': 7200,
        'DriverCarSLLastRPM': 7200,
        'DriverCarSLBlinkRPM': 7700,
        'DriverCarVersion': '2024.03.28.01',
        'DriverPitTrkPct': 0.031322,
        'DriverCarEstLapTime': 109.9309,
        'DriverSetupName': 'baseline.sto',
        'DriverSetupIsModified': 0,
        'DriverSetupLoadTypeName': 'baseline',
        'DriverSetupPassedTech': 1,
        'DriverIncidentCount': 0,
        'Drivers': [
          {
            'CarIdx': 0,
            'UserName': 'Pace Car',
            'AbbrevName': null,
            'Initials': null,
            'UserID': -1,
            'TeamID': 0,
            'TeamName': 'Pace Car',
            'CarNumber': '0',
            'CarNumberRaw': 0,
            'CarPath': 'safety pcporsche911cup',
            'CarClassID': 11,
            'CarID': 108,
            'CarIsPaceCar': 1,
            'CarIsAI': 0,
            'CarIsElectric': 0,
            'CarScreenName': 'safety pcporsche911cup',
            'CarScreenNameShort': 'safety pcporsche911cup',
            'CarClassShortName': null,
            'CarClassRelSpeed': 0,
            'CarClassLicenseLevel': 0,
            'CarClassMaxFuelPct': '1.000 %',
            'CarClassWeightPenalty': '0.000 kg',
            'CarClassPowerAdjust': '0.000 %',
            'CarClassDryTireSetLimit': '0 %',
            'CarClassColor': 16777215,
            'CarClassEstLapTime': 94.8244,
            'IRating': 0,
            'LicLevel': 1,
            'LicSubLevel': 0,
            'LicString': 'R 0.00',
            'LicColor': 16777215,
            'IsSpectator': 0,
            'CarDesignStr': '0,ffffff,ffffff,ffffff',
            'HelmetDesignStr': '0,ffffff,ffffff,ffffff',
            'SuitDesignStr': '0,ffffff,ffffff,ffffff',
            'BodyType': 0,
            'FaceType': 0,
            'HelmetType': 0,
            'CarNumberDesignStr': '0,0,ffffff,ffffff,ffffff',
            'CarSponsor_1': 0,
            'CarSponsor_2': 0,
            'ClubName': '-none-',
            'ClubID': 0,
            'DivisionName': 'Division 1',
            'DivisionID': 0,
            'CurDriverIncidentCount': -1,
            'TeamIncidentCount': -1
          },
          {
            'CarIdx': 1,
            'UserName': 'Wanda Grande',
            'AbbrevName': 'Grande, W',
            'Initials': 'WG',
            'UserID': 788826,
            'TeamID': 0,
            'TeamName': 'Wanda Grande',
            'CarNumber': '1',
            'CarNumberRaw': 1,
            'CarPath': 'mx5 mx52016',
            'CarClassID': 74,
            'CarID': 67,
            'CarIsPaceCar': 0,
            'CarIsAI': 0,
            'CarIsElectric': 0,
            'CarScreenName': 'Mazda MX-5 Cup',
            'CarScreenNameShort': 'MX-5 Cup',
            'CarClassShortName': 'MX5 Cup 2016',
            'CarClassRelSpeed': 35,
            'CarClassLicenseLevel': 0,
            'CarClassMaxFuelPct': '1.000 %',
            'CarClassWeightPenalty': '0.000 kg',
            'CarClassPowerAdjust': '0.000 %',
            'CarClassDryTireSetLimit': '0 %',
            'CarClassColor': 16777215,
            'CarClassEstLapTime': 109.9309,
            'IRating': 605,
            'LicLevel': 10,
            'LicSubLevel': 250,
            'LicString': 'C 2.50',
            'LicColor': 16706564,
            'IsSpectator': 0,
            'CarDesignStr': '21,060303,7de54c,1f2892;fdb805',
            'HelmetDesignStr': '19,0c0606,7de54c,1f2892',
            'SuitDesignStr': '35,040202,7de54c,1f2892',
            'BodyType': 1,
            'FaceType': 7,
            'HelmetType': 0,
            'CarNumberDesignStr': '0,0,ffffff,14f026,000000',
            'CarSponsor_1': 0,
            'CarSponsor_2': 0,
            'ClubName': 'Midwest',
            'ClubID': 29,
            'DivisionName': 'Division 9',
            'DivisionID': 8,
            'CurDriverIncidentCount': -1,
            'TeamIncidentCount': -1
          },
          {
            'CarIdx': 2,
            'UserName': 'Donatas Bertulis',
            'AbbrevName': 'Bertulis, D',
            'Initials': 'DB',
            'UserID': 1047429,
            'TeamID': 0,
            'TeamName': 'Donatas Bertulis',
            'CarNumber': '2',
            'CarNumberRaw': 2,
            'CarPath': 'mx5 mx52016',
            'CarClassID': 74,
            'CarID': 67,
            'CarIsPaceCar': 0,
            'CarIsAI': 0,
            'CarIsElectric': 0,
            'CarScreenName': 'Mazda MX-5 Cup',
            'CarScreenNameShort': 'MX-5 Cup',
            'CarClassShortName': 'MX5 Cup 2016',
            'CarClassRelSpeed': 35,
            'CarClassLicenseLevel': 0,
            'CarClassMaxFuelPct': '1.000 %',
            'CarClassWeightPenalty': '0.000 kg',
            'CarClassPowerAdjust': '0.000 %',
            'CarClassDryTireSetLimit': '0 %',
            'CarClassColor': 16777215,
            'CarClassEstLapTime': 109.9309,
            'IRating': 594,
            'LicLevel': 5,
            'LicSubLevel': 164,
            'LicString': 'D 1.64',
            'LicColor': 16550439,
            'IsSpectator': 0,
            'CarDesignStr': '1,dff000,1a4b9b,ffffff',
            'HelmetDesignStr': '1,dff000,1a4b9b,ffffff',
            'SuitDesignStr': '1,dff000,1a4b9b,ffffff',
            'BodyType': 0,
            'FaceType': 0,
            'HelmetType': 0,
            'CarNumberDesignStr': '0,0,ffffff,777777,000000',
            'CarSponsor_1': 0,
            'CarSponsor_2': 0,
            'ClubName': 'UK and I',
            'ClubID': 36,
            'DivisionName': 'Rookie',
            'DivisionID': 10,
            'CurDriverIncidentCount': -1,
            'TeamIncidentCount': -1
          },
          {
            'CarIdx': 3,
            'UserName': 'Thomas Haig',
            'AbbrevName': 'Haig, T',
            'Initials': 'TH',
            'UserID': 964912,
            'TeamID': 0,
            'TeamName': 'Thomas Haig',
            'CarNumber': '3',
            'CarNumberRaw': 3,
            'CarPath': 'mx5 mx52016',
            'CarClassID': 74,
            'CarID': 67,
            'CarIsPaceCar': 0,
            'CarIsAI': 0,
            'CarIsElectric': 0,
            'CarScreenName': 'Mazda MX-5 Cup',
            'CarScreenNameShort': 'MX-5 Cup',
            'CarClassShortName': 'MX5 Cup 2016',
            'CarClassRelSpeed': 35,
            'CarClassLicenseLevel': 0,
            'CarClassMaxFuelPct': '1.000 %',
            'CarClassWeightPenalty': '0.000 kg',
            'CarClassPowerAdjust': '0.000 %',
            'CarClassDryTireSetLimit': '0 %',
            'CarClassColor': 16777215,
            'CarClassEstLapTime': 109.9309,
            'IRating': 576,
            'LicLevel': 6,
            'LicSubLevel': 258,
            'LicString': 'D 2.58',
            'LicColor': 16550439,
            'IsSpectator': 0,
            'CarDesignStr': '6,121212,5eed1c,cccccc',
            'HelmetDesignStr': '62,1a00b7,ffffff,ff0000',
            'SuitDesignStr': '1,111111,ed1c24,cccccc',
            'BodyType': 0,
            'FaceType': 0,
            'HelmetType': 0,
            'CarNumberDesignStr': '0,0,ffffff,777777,000000',
            'CarSponsor_1': 147,
            'CarSponsor_2': 132,
            'ClubName': 'New England',
            'ClubID': 12,
            'DivisionName': 'Division 10',
            'DivisionID': 9,
            'CurDriverIncidentCount': -1,
            'TeamIncidentCount': -1
          },
          {
            'CarIdx': 4,
            'UserName': 'Jamani Ramsey',
            'AbbrevName': 'Ramsey, J',
            'Initials': 'JR',
            'UserID': 990218,
            'TeamID': 0,
            'TeamName': 'Jamani Ramsey',
            'CarNumber': '4',
            'CarNumberRaw': 4,
            'CarPath': 'mx5 mx52016',
            'CarClassID': 74,
            'CarID': 67,
            'CarIsPaceCar': 0,
            'CarIsAI': 0,
            'CarIsElectric': 0,
            'CarScreenName': 'Mazda MX-5 Cup',
            'CarScreenNameShort': 'MX-5 Cup',
            'CarClassShortName': 'MX5 Cup 2016',
            'CarClassRelSpeed': 35,
            'CarClassLicenseLevel': 0,
            'CarClassMaxFuelPct': '1.000 %',
            'CarClassWeightPenalty': '0.000 kg',
            'CarClassPowerAdjust': '0.000 %',
            'CarClassDryTireSetLimit': '0 %',
            'CarClassColor': 16777215,
            'CarClassEstLapTime': 109.9309,
            'IRating': 539,
            'LicLevel': 6,
            'LicSubLevel': 261,
            'LicString': 'D 2.61',
            'LicColor': 16550439,
            'IsSpectator': 0,
            'CarDesignStr': '14,ff0000,000000,111111',
            'HelmetDesignStr': '25,ff0000,ff0000,111111',
            'SuitDesignStr': '1,ff0000,ff0000,111111',
            'BodyType': 0,
            'FaceType': 10,
            'HelmetType': 0,
            'CarNumberDesignStr': '0,0,ffffff,777777,000000',
            'CarSponsor_1': 0,
            'CarSponsor_2': 0,
            'ClubName': 'International',
            'ClubID': 1,
            'DivisionName': 'Division 9',
            'DivisionID': 8,
            'CurDriverIncidentCount': -1,
            'TeamIncidentCount': -1
          },
          {
            'CarIdx': 5,
            'UserName': 'Brian Munn2',
            'AbbrevName': 'Munn2, B',
            'Initials': 'BM',
            'UserID': 1023147,
            'TeamID': 0,
            'TeamName': 'Brian Munn2',
            'CarNumber': '5',
            'CarNumberRaw': 5,
            'CarPath': 'mx5 mx52016',
            'CarClassID': 74,
            'CarID': 67,
            'CarIsPaceCar': 0,
            'CarIsAI': 0,
            'CarIsElectric': 0,
            'CarScreenName': 'Mazda MX-5 Cup',
            'CarScreenNameShort': 'MX-5 Cup',
            'CarClassShortName': 'MX5 Cup 2016',
            'CarClassRelSpeed': 35,
            'CarClassLicenseLevel': 0,
            'CarClassMaxFuelPct': '1.000 %',
            'CarClassWeightPenalty': '0.000 kg',
            'CarClassPowerAdjust': '0.000 %',
            'CarClassDryTireSetLimit': '0 %',
            'CarClassColor': 16777215,
            'CarClassEstLapTime': 109.9309,
            'IRating': 535,
            'LicLevel': 6,
            'LicSubLevel': 229,
            'LicString': 'D 2.29',
            'LicColor': 16550439,
            'IsSpectator': 0,
            'CarDesignStr': '10,000000,003bff,00ff3b.000000',
            'HelmetDesignStr': '11,faff00,00ff08,f7ff00',
            'SuitDesignStr': '15,0dff00,edff00,00ff05',
            'BodyType': 0,
            'FaceType': 4,
            'HelmetType': 0,
            'CarNumberDesignStr': '0,0,ffffff,777777,000000',
            'CarSponsor_1': 1,
            'CarSponsor_2': 2,
            'ClubName': 'Australia/NZ',
            'ClubID': 34,
            'DivisionName': 'Rookie',
            'DivisionID': 10,
            'CurDriverIncidentCount': -1,
            'TeamIncidentCount': -1
          },
          {
            'CarIdx': 6,
            'UserName': 'Harrison Sheppard',
            'AbbrevName': 'Sheppard, H',
            'Initials': 'HS',
            'UserID': 1041436,
            'TeamID': 0,
            'TeamName': 'Harrison Sheppard',
            'CarNumber': '6',
            'CarNumberRaw': 6,
            'CarPath': 'mx5 mx52016',
            'CarClassID': 74,
            'CarID': 67,
            'CarIsPaceCar': 0,
            'CarIsAI': 0,
            'CarIsElectric': 0,
            'CarScreenName': 'Mazda MX-5 Cup',
            'CarScreenNameShort': 'MX-5 Cup',
            'CarClassShortName': 'MX5 Cup 2016',
            'CarClassRelSpeed': 35,
            'CarClassLicenseLevel': 0,
            'CarClassMaxFuelPct': '1.000 %',
            'CarClassWeightPenalty': '0.000 kg',
            'CarClassPowerAdjust': '0.000 %',
            'CarClassDryTireSetLimit': '0 %',
            'CarClassColor': 16777215,
            'CarClassEstLapTime': 109.9309,
            'IRating': 533,
            'LicLevel': 6,
            'LicSubLevel': 231,
            'LicString': 'D 2.31',
            'LicColor': 16550439,
            'IsSpectator': 0,
            'CarDesignStr': '0,ffffff,ffffff,ff0011,000000',
            'HelmetDesignStr': '12,ffffff,ff0000,ff0000',
            'SuitDesignStr': '12,ffffff,000000,ff0011',
            'BodyType': 0,
            'FaceType': 4,
            'HelmetType': 0,
            'CarNumberDesignStr': '0,0,ffffff,ff0101,000000',
            'CarSponsor_1': 46,
            'CarSponsor_2': 47,
            'ClubName': 'UK and I',
            'ClubID': 36,
            'DivisionName': 'Rookie',
            'DivisionID': 10,
            'CurDriverIncidentCount': -1,
            'TeamIncidentCount': -1
          },
          {
            'CarIdx': 7,
            'UserName': 'Blaine Gibson',
            'AbbrevName': 'Gibson, B',
            'Initials': 'BG',
            'UserID': 892004,
            'TeamID': 0,
            'TeamName': 'Blaine Gibson',
            'CarNumber': '7',
            'CarNumberRaw': 7,
            'CarPath': 'mx5 mx52016',
            'CarClassID': 74,
            'CarID': 67,
            'CarIsPaceCar': 0,
            'CarIsAI': 0,
            'CarIsElectric': 0,
            'CarScreenName': 'Mazda MX-5 Cup',
            'CarScreenNameShort': 'MX-5 Cup',
            'CarClassShortName': 'MX5 Cup 2016',
            'CarClassRelSpeed': 35,
            'CarClassLicenseLevel': 0,
            'CarClassMaxFuelPct': '1.000 %',
            'CarClassWeightPenalty': '0.000 kg',
            'CarClassPowerAdjust': '0.000 %',
            'CarClassDryTireSetLimit': '0 %',
            'CarClassColor': 16777215,
            'CarClassEstLapTime': 109.9309,
            'IRating': 525,
            'LicLevel': 7,
            'LicSubLevel': 323,
            'LicString': 'D 3.23',
            'LicColor': 16550439,
            'IsSpectator': 0,
            'CarDesignStr': '4,666b92,2136ed,eeeeee;14dada',
            'HelmetDesignStr': '49,ffffff,ee3442,000000',
            'SuitDesignStr': '29,ffffff,ee3442,000000',
            'BodyType': 0,
            'FaceType': 0,
            'HelmetType': 0,
            'CarNumberDesignStr': '0,0,ffffff,777777,000000',
            'CarSponsor_1': 7,
            'CarSponsor_2': 241,
            'ClubName': 'Pennsylvania',
            'ClubID': 16,
            'DivisionName': 'Rookie',
            'DivisionID': 10,
            'CurDriverIncidentCount': -1,
            'TeamIncidentCount': -1
          },
          {
            'CarIdx': 8,
            'UserName': 'Jeremy M Adams',
            'AbbrevName': 'Adams, J',
            'Initials': 'JA',
            'UserID': 689122,
            'TeamID': 0,
            'TeamName': 'Jeremy M Adams',
            'CarNumber': '8',
            'CarNumberRaw': 8,
            'CarPath': 'mx5 mx52016',
            'CarClassID': 74,
            'CarID': 67,
            'CarIsPaceCar': 0,
            'CarIsAI': 0,
            'CarIsElectric': 0,
            'CarScreenName': 'Mazda MX-5 Cup',
            'CarScreenNameShort': 'MX-5 Cup',
            'CarClassShortName': 'MX5 Cup 2016',
            'CarClassRelSpeed': 35,
            'CarClassLicenseLevel': 0,
            'CarClassMaxFuelPct': '1.000 %',
            'CarClassWeightPenalty': '0.000 kg',
            'CarClassPowerAdjust': '0.000 %',
            'CarClassDryTireSetLimit': '0 %',
            'CarClassColor': 16777215,
            'CarClassEstLapTime': 109.9309,
            'IRating': 512,
            'LicLevel': 10,
            'LicSubLevel': 217,
            'LicString': 'C 2.17',
            'LicColor': 16706564,
            'IsSpectator': 0,
            'CarDesignStr': '19,0040ff,00f0cc,ffffff',
            'HelmetDesignStr': '57,be6009,000000,450883',
            'SuitDesignStr': '25,0b1098,000000,084082',
            'BodyType': 0,
            'FaceType': 6,
            'HelmetType': 0,
            'CarNumberDesignStr': '0,0,ffffff,777777,000000',
            'CarSponsor_1': 0,
            'CarSponsor_2': 0,
            'ClubName': 'New York',
            'ClubID': 14,
            'DivisionName': 'Division 10',
            'DivisionID': 9,
            'CurDriverIncidentCount': -1,
            'TeamIncidentCount': -1
          },
          {
            'CarIdx': 9,
            'UserName': 'Marcos Do Olival',
            'AbbrevName': 'Olival, M',
            'Initials': 'MO',
            'UserID': 1036190,
            'TeamID': 0,
            'TeamName': 'Marcos Do Olival',
            'CarNumber': '9',
            'CarNumberRaw': 9,
            'CarPath': 'mx5 mx52016',
            'CarClassID': 74,
            'CarID': 67,
            'CarIsPaceCar': 0,
            'CarIsAI': 0,
            'CarIsElectric': 0,
            'CarScreenName': 'Mazda MX-5 Cup',
            'CarScreenNameShort': 'MX-5 Cup',
            'CarClassShortName': 'MX5 Cup 2016',
            'CarClassRelSpeed': 35,
            'CarClassLicenseLevel': 0,
            'CarClassMaxFuelPct': '1.000 %',
            'CarClassWeightPenalty': '0.000 kg',
            'CarClassPowerAdjust': '0.000 %',
            'CarClassDryTireSetLimit': '0 %',
            'CarClassColor': 16777215,
            'CarClassEstLapTime': 109.9309,
            'IRating': 510,
            'LicLevel': 7,
            'LicSubLevel': 382,
            'LicString': 'D 3.82',
            'LicColor': 16550439,
            'IsSpectator': 0,
            'CarDesignStr': '6,f37807,cfc3c3,020202',
            'HelmetDesignStr': '36,ec8a08,d8cfcf,030303',
            'SuitDesignStr': '1,f4600c,a69e9e,090909',
            'BodyType': 0,
            'FaceType': 0,
            'HelmetType': 0,
            'CarNumberDesignStr': '0,0,ffffff,777777,000000',
            'CarSponsor_1': 0,
            'CarSponsor_2': 0,
            'ClubName': 'West',
            'ClubID': 32,
            'DivisionName': 'Rookie',
            'DivisionID': 10,
            'CurDriverIncidentCount': -1,
            'TeamIncidentCount': -1
          },
          {
            'CarIdx': 10,
            'UserName': 'Mohamed Kheroua',
            'AbbrevName': 'Kheroua, M',
            'Initials': 'MK',
            'UserID': 162087,
            'TeamID': 0,
            'TeamName': 'Mohamed Kheroua',
            'CarNumber': '10',
            'CarNumberRaw': 10,
            'CarPath': 'mx5 mx52016',
            'CarClassID': 74,
            'CarID': 67,
            'CarIsPaceCar': 0,
            'CarIsAI': 0,
            'CarIsElectric': 0,
            'CarScreenName': 'Mazda MX-5 Cup',
            'CarScreenNameShort': 'MX-5 Cup',
            'CarClassShortName': 'MX5 Cup 2016',
            'CarClassRelSpeed': 35,
            'CarClassLicenseLevel': 0,
            'CarClassMaxFuelPct': '1.000 %',
            'CarClassWeightPenalty': '0.000 kg',
            'CarClassPowerAdjust': '0.000 %',
            'CarClassDryTireSetLimit': '0 %',
            'CarClassColor': 16777215,
            'CarClassEstLapTime': 109.9309,
            'IRating': 650,
            'LicLevel': 2,
            'LicSubLevel': 280,
            'LicString': 'R 2.80',
            'LicColor': 16516870,
            'IsSpectator': 0,
            'CarDesignStr': '4,d7162d,efd600,111111',
            'HelmetDesignStr': '2,d7162d,efd600,111111',
            'SuitDesignStr': '1,d7162d,efd600,111111',
            'BodyType': 0,
            'FaceType': 0,
            'HelmetType': 0,
            'CarNumberDesignStr': '0,0,ffffff,777777,000000',
            'CarSponsor_1': 50,
            'CarSponsor_2': 124,
            'ClubName': 'France',
            'ClubID': 39,
            'DivisionName': 'Rookie',
            'DivisionID': 10,
            'CurDriverIncidentCount': -1,
            'TeamIncidentCount': -1
          },
          {
            'CarIdx': 11,
            'UserName': 'Gabe Guevara',
            'AbbrevName': 'Guevara, G',
            'Initials': 'GG',
            'UserID': 1010670,
            'TeamID': 0,
            'TeamName': 'Gabe Guevara',
            'CarNumber': '11',
            'CarNumberRaw': 11,
            'CarPath': 'mx5 mx52016',
            'CarClassID': 74,
            'CarID': 67,
            'CarIsPaceCar': 0,
            'CarIsAI': 0,
            'CarIsElectric': 0,
            'CarScreenName': 'Mazda MX-5 Cup',
            'CarScreenNameShort': 'MX-5 Cup',
            'CarClassShortName': 'MX5 Cup 2016',
            'CarClassRelSpeed': 35,
            'CarClassLicenseLevel': 0,
            'CarClassMaxFuelPct': '1.000 %',
            'CarClassWeightPenalty': '0.000 kg',
            'CarClassPowerAdjust': '0.000 %',
            'CarClassDryTireSetLimit': '0 %',
            'CarClassColor': 16777215,
            'CarClassEstLapTime': 109.9309,
            'IRating': 495,
            'LicLevel': 10,
            'LicSubLevel': 256,
            'LicString': 'C 2.56',
            'LicColor': 16706564,
            'IsSpectator': 0,
            'CarDesignStr': '11,096631,ffffff,000000;474747',
            'HelmetDesignStr': '43,214018,ffffff,000000',
            'SuitDesignStr': '4,153d10,ffffff,111111',
            'BodyType': 0,
            'FaceType': 8,
            'HelmetType': 0,
            'CarNumberDesignStr': '0,0,ffffff,777777,000000',
            'CarSponsor_1': 221,
            'CarSponsor_2': 62,
            'ClubName': 'Texas',
            'ClubID': 30,
            'DivisionName': 'Division 9',
            'DivisionID': 8,
            'CurDriverIncidentCount': -1,
            'TeamIncidentCount': -1
          },
          {
            'CarIdx': 63,
            'UserName': 'Alptug Idin2',
            'AbbrevName': null,
            'Initials': null,
            'UserID': 1041895,
            'TeamID': 0,
            'TeamName': 'Alptug Idin2',
            'CarNumber': '907',
            'CarNumberRaw': 907,
            'CarPath': 'mx5 mx52016',
            'CarClassID': 74,
            'CarID': 67,
            'CarIsPaceCar': 0,
            'CarIsAI': 0,
            'CarIsElectric': 0,
            'CarScreenName': 'Mazda MX-5 Cup',
            'CarScreenNameShort': 'MX-5 Cup',
            'CarClassShortName': 'MX5 Cup 2016',
            'CarClassRelSpeed': 35,
            'CarClassLicenseLevel': 0,
            'CarClassMaxFuelPct': '1.000 %',
            'CarClassWeightPenalty': '0.000 kg',
            'CarClassPowerAdjust': '0.000 %',
            'CarClassDryTireSetLimit': '0 %',
            'CarClassColor': 16777215,
            'CarClassEstLapTime': 109.9309,
            'IRating': 1335,
            'LicLevel': 7,
            'LicSubLevel': 361,
            'LicString': 'D 3.61',
            'LicColor': 16550439,
            'IsSpectator': 1,
            'CarDesignStr': '14,103673,f2ff00,068453,ffffff',
            'HelmetDesignStr': '22,068453,103673,fced00',
            'SuitDesignStr': '2,103673,fced00,068453',
            'BodyType': 0,
            'FaceType': 0,
            'HelmetType': 0,
            'CarNumberDesignStr': '0,0,000000,777777,ffffff',
            'CarSponsor_1': 83,
            'CarSponsor_2': 2,
            'ClubName': 'International',
            'ClubID': 1,
            'DivisionName': 'Rookie',
            'DivisionID': 10,
            'CurDriverIncidentCount': 0,
            'TeamIncidentCount': 0
          }
        ]
      },
      'SplitTimeInfo': {
        'Sectors': [
          {
            'SectorNum': 0,
            'SectorStartPct': 0
          },
          {
            'SectorNum': 1,
            'SectorStartPct': 0.1373
          },
          {
            'SectorNum': 2,
            'SectorStartPct': 0.278969
          },
          {
            'SectorNum': 3,
            'SectorStartPct': 0.450235
          },
          {
            'SectorNum': 4,
            'SectorStartPct': 0.561539
          },
          {
            'SectorNum': 5,
            'SectorStartPct': 0.737827
          },
          {
            'SectorNum': 6,
            'SectorStartPct': 0.879426
          }
        ]
      },
      'CarSetup': {
        'UpdateCount': 1,
        'Suspension': {
          'Front': {
            'ToeIn': '-1.5 mm',
            'CrossWeight': '50.1%',
            'AntiRollBar': 'Firm'
          },
          'LeftFront': {
            'ColdPressure': '207 kPa',
            'LastHotPressure': '207 kPa',
            'LastTempsOMI': '26C, 26C, 26C',
            'TreadRemaining': '100%, 100%, 100%',
            'CornerWeight': '2687 N',
            'RideHeight': '116 mm',
            'SpringPerchOffset': '70.5 mm',
            'BumpStiffness': '+9 clicks',
            'ReboundStiffness': '+8 clicks',
            'Camber': '-4.6 deg'
          },
          'LeftRear': {
            'ColdPressure': '207 kPa',
            'LastHotPressure': '207 kPa',
            'LastTempsOMI': '26C, 26C, 26C',
            'TreadRemaining': '100%, 100%, 100%',
            'CornerWeight': '2419 N',
            'RideHeight': '116 mm',
            'SpringPerchOffset': '65.5 mm',
            'BumpStiffness': '+6 clicks',
            'ReboundStiffness': '+5 clicks',
            'Camber': '-3.6 deg'
          },
          'RightFront': {
            'ColdPressure': '207 kPa',
            'LastHotPressure': '207 kPa',
            'LastTempsIMO': '26C, 26C, 26C',
            'TreadRemaining': '100%, 100%, 100%',
            'CornerWeight': '2465 N',
            'RideHeight': '116 mm',
            'SpringPerchOffset': '77.5 mm',
            'BumpStiffness': '+9 clicks',
            'ReboundStiffness': '+8 clicks',
            'Camber': '-4.6 deg'
          },
          'RightRear': {
            'ColdPressure': '207 kPa',
            'LastHotPressure': '207 kPa',
            'LastTempsIMO': '26C, 26C, 26C',
            'TreadRemaining': '100%, 100%, 100%',
            'CornerWeight': '2175 N',
            'RideHeight': '116 mm',
            'SpringPerchOffset': '70.0 mm',
            'BumpStiffness': '+6 clicks',
            'ReboundStiffness': '+5 clicks',
            'Camber': '-3.6 deg'
          },
          'Rear': {
            'FuelLevel': '23.8 L',
            'ToeIn': '+0.3 mm',
            'AntiRollBar': 'Unhooked'
          }
        }
      }
    }
  },
  telemetry: {
    "timestamp": "2024-05-05T14:26:08.043Z",
    "values": {
      "SessionTime": 872.6333394363263,
      "SessionTick": 83915,
      "SessionNum": 2,
      "SessionState": "Racing",
      "SessionUniqueID": 3,
      "SessionFlags": [
        "StartHidden"
      ],
      "SessionTimeRemain": 604800,
      "SessionLapsRemain": 1,
      "SessionLapsRemainEx": 2,
      "SessionTimeTotal": 604800,
      "SessionLapsTotal": 8,
      "SessionJokerLapsRemain": 0,
      "SessionOnJokerLap": false,
      "SessionTimeOfDay": 52172,
      "RadioTransmitCarIdx": -1,
      "RadioTransmitRadioIdx": 0,
      "RadioTransmitFrequencyIdx": 0,
      "DisplayUnits": 1,
      "DriverMarker": false,
      "PushToTalk": false,
      "PushToPass": false,
      "ManualBoost": false,
      "ManualNoBoost": false,
      "IsOnTrack": false,
      "IsReplayPlaying": true,
      "ReplayFrameNum": 34472,
      "ReplayFrameNumEnd": 1,
      "IsDiskLoggingEnabled": false,
      "IsDiskLoggingActive": false,
      "FrameRate": 114.48384094238281,
      "CpuUsageFG": 0.4276885986328125,
      "GpuUsage": 0.4219144880771637,
      "ChanAvgLatency": 0.16685080528259277,
      "ChanLatency": 0.1666666716337204,
      "ChanQuality": 1.0000172853469849,
      "ChanPartnerQuality": 1,
      "CpuUsageBG": 0.3049992024898529,
      "ChanClockSkew": 0,
      "MemPageFaultSec": 0,
      "MemSoftPageFaultSec": 0,
      "PlayerCarPosition": 0,
      "PlayerCarClassPosition": 0,
      "PlayerCarClass": 74,
      "PlayerTrackSurface": "NotInWorld",
      "PlayerTrackSurfaceMaterial": "SurfaceNotInWorld",
      "PlayerCarIdx": 63,
      "PlayerCarTeamIncidentCount": 0,
      "PlayerCarMyIncidentCount": 0,
      "PlayerCarDriverIncidentCount": 0,
      "PlayerCarWeightPenalty": 0,
      "PlayerCarPowerAdjust": 0,
      "PlayerCarDryTireSetLimit": 0,
      "PlayerCarTowTime": 0,
      "PlayerCarInPitStall": false,
      "PlayerCarPitSvStatus": "PitSvNone",
      "PlayerTireCompound": -1,
      "PlayerFastRepairsUsed": 0,
      "CarIdxLap": [
        0,
        3,
        6,
        7,
        6,
        7,
        -1,
        6,
        6,
        6,
        7,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      "CarIdxLapCompleted": [
        -1,
        2,
        5,
        6,
        5,
        6,
        -1,
        5,
        5,
        5,
        6,
        5,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      "CarIdxLapDistPct": [
        0.03374706208705902,
        0.21841421723365784,
        0.2758820354938507,
        0.18559664487838745,
        0.8599201440811157,
        0.21168194711208344,
        -1,
        0.3386056423187256,
        0.39362239837646484,
        0.3545111119747162,
        0.3834777772426605,
        0.09396719187498093,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      "CarIdxTrackSurface": [
        "AproachingPits",
        "OffTrack",
        "OnTrack",
        "OnTrack",
        "OnTrack",
        "OnTrack",
        "NotInWorld",
        "OnTrack",
        "OnTrack",
        "OnTrack",
        "OnTrack",
        "OnTrack",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld",
        "NotInWorld"
      ],
      "CarIdxTrackSurfaceMaterial": [
        "Asphalt1Material",
        "Grass2Material",
        "Asphalt1Material",
        "Asphalt1Material",
        "Asphalt1Material",
        "Asphalt1Material",
        "SurfaceNotInWorld",
        "Asphalt1Material",
        "Asphalt1Material",
        "Asphalt1Material",
        "Asphalt1Material",
        "Asphalt1Material",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld",
        "SurfaceNotInWorld"
      ],
      "CarIdxOnPitRoad": [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "CarIdxPosition": [
        0,
        10,
        8,
        3,
        4,
        2,
        0,
        7,
        5,
        6,
        1,
        9,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "CarIdxClassPosition": [ // burası resıl
        0,
        10,
        8,
        3,
        4,
        2,
        0,
        7,
        5,
        6,
        1,
        9,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "CarIdxClass": [
        11,
        74,
        74,
        74,
        74,
        74,
        74,
        74,
        74,
        74,
        74,
        74,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        74
      ],
      "CarIdxF2Time": [
        0,
        27.793899536132812,
        124.74659729003906,
        20.08930015563965,
        49.05759811401367,
        16.684999465942383,
        0,
        118.22979736328125,
        103.80829620361328,
        117.1250991821289,
        0,
        142.85890197753906,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "CarIdxEstTime": [
        2.4969735145568848,
        22.41459083557129,
        27.858203887939453,
        18.89358139038086,
        94.14568328857422,
        21.720226287841797,
        0,
        33.361690521240234,
        40.00985336303711,
        34.76726150512695,
        38.24637222290039,
        9.728328704833984,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "CarIdxLastLapTime": [
        -1,
        132.2230987548828,
        117.177001953125,
        116.9916000366211,
        122.24559783935547,
        122.36329650878906,
        -1,
        118.9480972290039,
        183.60459899902344,
        119.6989974975586,
        114.09529876708984,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      "CarIdxBestLapTime": [
        -1,
        -1,
        116.93260192871094,
        116.9916000366211,
        122.24559783935547,
        115.88150024414062,
        -1,
        117.15019989013672,
        120.4697036743164,
        119.6989974975586,
        114.59629821777344,
        120.97899627685547,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      "CarIdxBestLapNum": [
        -1,
        -1,
        4,
        6,
        5,
        3,
        -1,
        4,
        3,
        5,
        4,
        2,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      "CarIdxTireCompound": [
        -1,
        0,
        0,
        0,
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        0,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      "CarIdxQualTireCompound": [
        -1,
        0,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      "CarIdxQualTireCompoundLocked": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "CarIdxFastRepairsUsed": [
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "CarIdxSessionFlags": [
        [
          "Servicible"
        ],
        [
          "Servicible"
        ],
        [
          "Servicible"
        ],
        [
          "Servicible"
        ],
        [
          "Servicible"
        ],
        [
          "Servicible"
        ],
        [],
        [
          "Servicible"
        ],
        [
          "Servicible"
        ],
        [
          "Servicible"
        ],
        [
          "Servicible"
        ],
        [
          "Servicible"
        ],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        []
      ],
      "PaceMode": 1,
      "CarIdxPaceLine": [
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      "CarIdxPaceRow": [
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      "CarIdxPaceFlags": [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        []
      ],
      "OnPitRoad": false,
      "CarIdxSteer": [
        -1.8535804002794976e-8,
        2.4806949827649305e-9,
        -0.09298714250326157,
        -0.35768410563468933,
        -0.05129261687397957,
        -0.07036056369543076,
        0,
        -0.2891581654548645,
        -0.9309744238853455,
        -0.01301853358745575,
        -0.696774423122406,
        0.02038286067545414,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "CarIdxRPM": [
        2000,
        872.8905029296875,
        6433.4130859375,
        5903.10009765625,
        6915.333984375,
        6142.2216796875,
        -1,
        6264.23486328125,
        6090.0859375,
        6191.24755859375,
        4488.40087890625,
        6107.88330078125,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      "CarIdxGear": [
        1,
        3,
        4,
        3,
        3,
        3,
        -1,
        4,
        1,
        4,
        2,
        3,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      "SteeringWheelAngle": 0,
      "Throttle": 0,
      "Brake": 1,
      "Clutch": 0,
      "Gear": 0,
      "RPM": 300,
      "PlayerCarSLFirstRPM": 5600,
      "PlayerCarSLShiftRPM": 7200,
      "PlayerCarSLLastRPM": 7200,
      "PlayerCarSLBlinkRPM": 7700,
      "Lap": 0,
      "LapCompleted": 0,
      "LapDist": 0,
      "LapDistPct": 0,
      "RaceLaps": 7,
      "LapBestLap": 0,
      "LapBestLapTime": 0,
      "LapLastLapTime": 0,
      "LapCurrentLapTime": 0,
      "LapLasNLapSeq": 0,
      "LapLastNLapTime": 0,
      "LapBestNLapLap": 0,
      "LapBestNLapTime": 0,
      "LapDeltaToBestLap": 0,
      "LapDeltaToBestLap_DD": 0,
      "LapDeltaToBestLap_OK": false,
      "LapDeltaToOptimalLap": 0,
      "LapDeltaToOptimalLap_DD": 0,
      "LapDeltaToOptimalLap_OK": false,
      "LapDeltaToSessionBestLap": 0,
      "LapDeltaToSessionBestLap_DD": 0,
      "LapDeltaToSessionBestLap_OK": false,
      "LapDeltaToSessionOptimalLap": 0,
      "LapDeltaToSessionOptimalLap_DD": 0,
      "LapDeltaToSessionOptimalLap_OK": false,
      "LapDeltaToSessionLastlLap": 0,
      "LapDeltaToSessionLastlLap_DD": 0,
      "LapDeltaToSessionLastlLap_OK": false,
      "Speed": 0,
      "Yaw": 0,
      "YawNorth": 0,
      "Pitch": 0,
      "Roll": 0,
      "EnterExitReset": 0,
      "TrackTemp": 33.333343505859375,
      "TrackTempCrew": 33.333343505859375,
      "AirTemp": 20.0616455078125,
      "TrackWetness": 1,
      "Skies": 2,
      "AirDensity": 1.2029142379760742,
      "AirPressure": 101549.3828125,
      "WindVel": 1.8355075120925903,
      "WindDir": 3.5971057415008545,
      "RelativeHumidity": 0.345954567193985,
      "FogLevel": 0,
      "Precipitation": 0,
      "SolarAltitude": 0.8632321953773499,
      "SolarAzimuth": 3.6893205642700195,
      "WeatherDeclaredWet": false,
      "DCLapStatus": 2,
      "DCDriversSoFar": 0,
      "OkToReloadTextures": true,
      "LoadNumTextures": false,
      "CarLeftRight": 0,
      "PitsOpen": true,
      "VidCapEnabled": false,
      "VidCapActive": false,
      "PitRepairLeft": 0,
      "PitOptRepairLeft": 0,
      "PitstopActive": false,
      "FastRepairUsed": 0,
      "FastRepairAvailable": 0,
      "LFTiresUsed": 0,
      "RFTiresUsed": 0,
      "LRTiresUsed": 0,
      "RRTiresUsed": 0,
      "LeftTireSetsUsed": 0,
      "RightTireSetsUsed": 0,
      "FrontTireSetsUsed": 0,
      "RearTireSetsUsed": 0,
      "TireSetsUsed": 0,
      "LFTiresAvailable": 0,
      "RFTiresAvailable": 0,
      "LRTiresAvailable": 0,
      "RRTiresAvailable": 0,
      "LeftTireSetsAvailable": 0,
      "RightTireSetsAvailable": 0,
      "FrontTireSetsAvailable": 0,
      "RearTireSetsAvailable": 0,
      "TireSetsAvailable": 0,
      "CamCarIdx": 11,
      "CamCameraNumber": 1,
      "CamGroupNumber": 18,
      "CamCameraState": [
        "IsSessionScreen",
        "UseAutoShotSelection",
        "UseKeyAcceleration"
      ],
      "IsOnTrackCar": false,
      "IsInGarage": false,
      "SteeringWheelAngleMax": 17.278644561767578,
      "ShiftPowerPct": 0,
      "ShiftGrindRPM": 0,
      "ThrottleRaw": 0,
      "BrakeRaw": 0,
      "ClutchRaw": 0,
      "HandbrakeRaw": 0,
      "BrakeABSactive": false,
      "EngineWarnings": [],
      "FuelLevelPct": 0,
      "PitSvFlags": [],
      "PitSvLFP": 0,
      "PitSvRFP": 0,
      "PitSvLRP": 0,
      "PitSvRRP": 0,
      "PitSvFuel": 0,
      "PitSvTireCompound": 0,
      "CarIdxP2P_Status": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "CarIdxP2P_Count": [
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      "SteeringWheelPctTorque": 0,
      "SteeringWheelPctTorqueSign": 0,
      "SteeringWheelPctTorqueSignStops": 0,
      "SteeringWheelPctIntensity": 0,
      "SteeringWheelPctSmoothing": 0,
      "SteeringWheelPctDamper": 0,
      "SteeringWheelLimiter": 0,
      "SteeringWheelMaxForceNm": 28.33333396911621,
      "SteeringWheelPeakForceNm": -1,
      "SteeringWheelUseLinear": true,
      "ShiftIndicatorPct": 0,
      "ReplayPlaySpeed": 1,
      "ReplayPlaySlowMotion": false,
      "ReplaySessionTime": 871.6266520182292,
      "ReplaySessionNum": 2,
      "TireLF_RumblePitch": 0,
      "TireRF_RumblePitch": 0,
      "TireLR_RumblePitch": 0,
      "TireRR_RumblePitch": 0,
      "IsGarageVisible": false,
      "SteeringWheelTorque_ST": [
        0.17248526215553284,
        0.17248526215553284,
        0.17248526215553284,
        0.17248526215553284,
        0.17248526215553284,
        0.17248526215553284
      ],
      "SteeringWheelTorque": 0.17248526215553284,
      "VelocityZ_ST": [
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "VelocityY_ST": [
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "VelocityX_ST": [
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "VelocityZ": 0,
      "VelocityY": 0,
      "VelocityX": 0,
      "YawRate_ST": [
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "PitchRate_ST": [
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "RollRate_ST": [
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "YawRate": 0,
      "PitchRate": 0,
      "RollRate": 0,
      "VertAccel_ST": [
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "LatAccel_ST": [
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "LongAccel_ST": [
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "VertAccel": 0,
      "LatAccel": 0,
      "LongAccel": 0,
      "dcStarter": false,
      "dcPitSpeedLimiterToggle": false,
      "dpRFTireChange": 0,
      "dpLFTireChange": 0,
      "dpRRTireChange": 0,
      "dpLRTireChange": 0,
      "dpFuelFill": 0,
      "dpFuelAutoFillEnabled": 0,
      "dpFuelAutoFillActive": 0,
      "dpWindshieldTearoff": 0,
      "dpFuelAddKg": 0,
      "dpFastRepair": 0,
      "dpLFTireColdPress": 0,
      "dpRFTireColdPress": 0,
      "dpLRTireColdPress": 0,
      "dpRRTireColdPress": 0,
      "FuelUsePerHour": 0,
      "Voltage": 12.40000057220459,
      "WaterTemp": 77,
      "WaterLevel": 5,
      "FuelPress": 0,
      "OilTemp": 77,
      "OilPress": 0,
      "OilLevel": 6.400000095367432,
      "ManifoldPress": 1,
      "FuelLevel": 0,
      "Engine0_RPM": 0,
      "RFbrakeLinePress": 0,
      "RFcoldPressure": 206.8427276611328,
      "RFtempCL": 25.993743896484375,
      "RFtempCM": 25.993743896484375,
      "RFtempCR": 25.993743896484375,
      "RFwearL": 1,
      "RFwearM": 1,
      "RFwearR": 1,
      "LFbrakeLinePress": 0,
      "LFcoldPressure": 206.8427276611328,
      "LFtempCL": 25.993743896484375,
      "LFtempCM": 25.993743896484375,
      "LFtempCR": 25.993743896484375,
      "LFwearL": 1,
      "LFwearM": 1,
      "LFwearR": 1,
      "RRbrakeLinePress": 0,
      "RRcoldPressure": 206.8427276611328,
      "RRtempCL": 25.993743896484375,
      "RRtempCM": 25.993743896484375,
      "RRtempCR": 25.993743896484375,
      "RRwearL": 1,
      "RRwearM": 1,
      "RRwearR": 1,
      "LRbrakeLinePress": 0,
      "LRcoldPressure": 206.8427276611328,
      "LRtempCL": 25.993743896484375,
      "LRtempCM": 25.993743896484375,
      "LRtempCR": 25.993743896484375,
      "LRwearL": 1,
      "LRwearM": 1,
      "LRwearR": 1,
      "LRshockDefl": 0.10147207975387573,
      "LRshockDefl_ST": [
        0.10147207975387573,
        0.10147207975387573,
        0.10147207975387573,
        0.10147207975387573,
        0.10147207975387573,
        0.10147207975387573
      ],
      "LRshockVel": 1.6421705484390259,
      "LRshockVel_ST": [
        1.6421705484390259,
        1.6421705484390259,
        1.6421705484390259,
        1.6421705484390259,
        1.6421705484390259,
        1.6421705484390259
      ],
      "RRshockDefl": 0.10147199034690857,
      "RRshockDefl_ST": [
        0.10147199034690857,
        0.10147199034690857,
        0.10147199034690857,
        0.10147199034690857,
        0.10147199034690857,
        0.10147199034690857
      ],
      "RRshockVel": 1.6413038969039917,
      "RRshockVel_ST": [
        1.6413038969039917,
        1.6413038969039917,
        1.6413038969039917,
        1.6413038969039917,
        1.6413038969039917,
        1.6413038969039917
      ],
      "LFshockDefl": 0.10137565433979034,
      "LFshockDefl_ST": [
        0.10137565433979034,
        0.10137565433979034,
        0.10137565433979034,
        0.10137565433979034,
        0.10137565433979034,
        0.10137565433979034
      ],
      "LFshockVel": 1.1312520503997803,
      "LFshockVel_ST": [
        1.1312520503997803,
        1.1312520503997803,
        1.1312520503997803,
        1.1312520503997803,
        1.1312520503997803,
        1.1312520503997803
      ],
      "RFshockDefl": 0.10141441226005554,
      "RFshockDefl_ST": [
        0.10141441226005554,
        0.10141441226005554,
        0.10141441226005554,
        0.10141441226005554,
        0.10141441226005554,
        0.10141441226005554
      ],
      "RFshockVel": 1.1551727056503296,
      "RFshockVel_ST": [
        1.1551727056503296,
        1.1551727056503296,
        1.1551727056503296,
        1.1551727056503296,
        1.1551727056503296,
        1.1551727056503296
      ]
    }
  }
};

